# ┌──────────────────────────────┐
# │          Autostart           │
# └──────────────────────────────┘

# Panel
exec-once = hyprpanel

# Wallpaper
exec-once = awww-daemon

# Notifications
exec-once = swaync

# Clipboard
exec-once = wl-clipboard-store
exec-once = cliphist store

# Idle & Lock
exec-once = hypridle

# Curseur
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
