# ╔══════════════════════════════════════════════╗
# ║          Colony Desktop — by Lin & EVE       ║
# ║              Hyprland Config 💜               ║
# ╚══════════════════════════════════════════════╝

# Config modulaire
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
